version: '3'
services:
    app:
        container_name: app
        build:
            context: ./node
            dockerfile: Dockerfile
        working_dir: /var/www
        tty: true
        volumes:
            - ../:/var/www