version: '3'
services:
    app:
        container_name: app
        build:
            context: ./node
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - ../data-excel/:/var/www/data-excel